import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { NexApiClient } from "../client.js";

export function registerNotificationTools(server: McpServer, client: NexApiClient) {
  server.tool(
    "get_notifications",
    "List recent notification feed items. Returns context alerts with important items and entity changes that were generated by the server-side notification system.",
    {
      limit: z.number().optional().describe("Max results (default: 20, max: 50)"),
      since: z.string().optional().describe("Only items sent after this ISO8601 timestamp"),
    },
    { readOnlyHint: true },
    async ({ limit, since }) => {
      const params = new URLSearchParams();
      if (limit !== undefined) params.set("limit", String(limit));
      if (since) params.set("since", since);
      const qs = params.toString();
      const path = `/v1/notifications/feed${qs ? `?${qs}` : ""}`;
      const result = await client.get(path);
      return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
    },
  );

  server.tool(
    "get_notification_preferences",
    "Get current notification preferences: polling frequency, enabled notification types, and digest settings.",
    {},
    { readOnlyHint: true },
    async () => {
      const result = await client.get("/v1/notifications/preferences");
      return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
    },
  );

  server.tool(
    "set_notification_preferences",
    "Update notification preferences: polling frequency, enabled types, or digest settings.",
    {
      frequency_minutes: z.number().min(1).optional().describe("Polling interval in minutes"),
      enabled_types: z.array(z.string()).optional().describe("Notification types to enable"),
      digest_enabled: z.boolean().optional().describe("Enable or disable daily digest"),
    },
    { readOnlyHint: false },
    async ({ frequency_minutes, enabled_types, digest_enabled }) => {
      const body: Record<string, unknown> = {};
      if (frequency_minutes !== undefined) body.frequency_minutes = frequency_minutes;
      if (enabled_types !== undefined) body.enabled_types = enabled_types;
      if (digest_enabled !== undefined) body.digest_enabled = digest_enabled;
      const result = await client.patch("/v1/notifications/preferences", body);
      return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
    },
  );

  server.tool(
    "create_notification_rule",
    "Create a custom AI notification rule. Describe what you want to be notified about in natural language, e.g. 'notify me when deal value changes by more than 10%'.",
    {
      description: z.string().min(1).describe("Natural language description of the notification rule"),
    },
    { readOnlyHint: false },
    async ({ description }) => {
      const result = await client.post("/v1/notifications/custom", { description });
      return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
    },
  );

  server.tool(
    "list_notification_rules",
    "List all custom notification rules you have set up.",
    {},
    { readOnlyHint: true },
    async () => {
      const result = await client.get("/v1/notifications/custom");
      return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
    },
  );

  server.tool(
    "delete_notification_rule",
    "Delete a custom notification rule by ID.",
    {
      rule_id: z.string().describe("The notification rule ID to delete"),
    },
    { readOnlyHint: false, destructiveHint: true },
    async ({ rule_id }) => {
      const result = await client.delete(`/v1/notifications/custom/${encodeURIComponent(rule_id)}`);
      return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
    },
  );
}
